[package]
name = "feather_wallet"
version = "0.0.3"
authors = ["lsaether <Lsaether@protonmail.com>"]

[dependencies]
base64 = "0.7.0"
bip39 = "0.4.1"
rand = "0.3"
ring-pwhash = { path = "../ring-pwhash/" }